"use client"
import { useState, useMemo } from "react"
import { BikeCard } from "@/components/bike-card"
import { Header } from "@/components/header"
import { HeroSection } from "@/components/hero-section"
import { SpecsSection } from "@/components/specs-section"

const royalEnfieldBikes = [
  {
    id: 1,
    name: "Classic 350",
    image: "/black-vintage-royal-enfield.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "349cc",
    torque: "27 Nm @ 4000 rpm",
    power: "20.2 bhp @ 6100 rpm",
    topSpeed: "104 km/h",
    mileage: "35-40 kmpl",
    fuelCapacity: "13 L",
    weight: "195 kg",
    price: "₹1,93,000",
    description:
      "The timeless Classic 350 embodies Royal Enfield's heritage with modern reliability and authentic British charm.",
    features: ["Electric Start", "Dual Channel ABS", "Tripper Navigation Ready"],
    colors: ["Stealth Black", "Chrome Black", "Dark Green", "Halcyon Black"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/classic-350/",
    year: 2023,
    category: "new",
  },
  {
    id: 2,
    name: "Bullet 350",
    image: "/royal-enfield-classic-black.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.1 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "192 kg",
    price: "₹1,48,000",
    description:
      "The legendary Bullet 350 - where Royal Enfield's story began, delivering pure, uncompromising motorcycling essence.",
    features: ["Kick Start", "Single Channel ABS", "Classic Styling"],
    colors: ["Onyx Black", "Regal Red", "Royal Blue"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/bullet-350/",
    year: 2023,
    category: "new",
  },
  {
    id: 3,
    name: "Himalayan",
    image: "/placeholder-lqd2v.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "411cc",
    torque: "32 Nm @ 4250 rpm",
    power: "24.3 bhp @ 6500 rpm",
    topSpeed: "120 km/h",
    mileage: "30-35 kmpl",
    fuelCapacity: "15 L",
    weight: "199 kg",
    price: "₹2,16,000",
    description:
      "Built for adventure seekers, the Himalayan conquers every terrain with unwavering confidence and rugged determination.",
    features: ["Long Travel Suspension", "Dual Purpose Tyres", "Compass & Tripper Pod"],
    colors: ["Granite Black", "Mirage Silver", "Pine Green", "Rock Red"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/himalayan/",
    year: 2023,
    category: "new",
  },
  {
    id: 4,
    name: "Continental GT 650",
    image: "/placeholder-sshcq.png",
    engine: "Parallel Twin, 4-Stroke, Air-Oil Cooled",
    displacement: "648cc",
    torque: "52 Nm @ 4000 rpm",
    power: "47 bhp @ 7250 rpm",
    topSpeed: "160 km/h",
    mileage: "25-30 kmpl",
    fuelCapacity: "12.5 L",
    weight: "198 kg",
    price: "₹3,05,000",
    description:
      "The Continental GT 650 - a modern cafe racer masterpiece that perfectly blends vintage aesthetics with contemporary performance.",
    features: ["Twin Cylinder Engine", "Clip-on Handlebars", "Pirelli Tyres"],
    colors: ["Ventura Storm", "British Racing Green", "Mister Clean", "Rocker Red"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/continental-gt-650/",
    year: 2023,
    category: "new",
  },
  {
    id: 5,
    name: "Interceptor 650",
    image: "/royal-enfield-interceptor-650-orange.png",
    engine: "Parallel Twin, 4-Stroke, Air-Oil Cooled",
    displacement: "648cc",
    torque: "52 Nm @ 4000 rpm",
    power: "47 bhp @ 7250 rpm",
    topSpeed: "160 km/h",
    mileage: "25-30 kmpl",
    fuelCapacity: "13.7 L",
    weight: "202 kg",
    price: "₹2,98,000",
    description:
      "The Interceptor 650 delivers exhilarating twin-cylinder performance wrapped in timeless British motorcycle styling.",
    features: ["Twin Cylinder Engine", "Comfortable Riding Position", "Chrome Finish"],
    colors: ["Orange Crush", "Baker Express", "Ravishing Red", "Mark Three Black"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/interceptor-650/",
    year: 2023,
    category: "new",
  },
  {
    id: 6,
    name: "Meteor 350",
    image: "/royal-enfield-meteor-350-fireball-red.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "349cc",
    torque: "27 Nm @ 4000 rpm",
    power: "20.2 bhp @ 6100 rpm",
    topSpeed: "115 km/h",
    mileage: "36-41 kmpl",
    fuelCapacity: "15 L",
    weight: "191 kg",
    price: "₹2,01,000",
    description:
      "The Meteor 350 - your perfect gateway to effortless cruising and endless highway adventures with modern comfort.",
    features: ["Tripper Navigation", "LED Lighting", "Comfortable Cruiser Ergonomics"],
    colors: ["Fireball", "Stellar", "Supernova"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/meteor-350/",
    year: 2023,
    category: "new",
  },
  {
    id: 7,
    name: "Standard 350 (2024)",
    image: "/royal-enfield-standard-350-2024.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "349cc",
    torque: "27 Nm @ 4000 rpm",
    power: "20.2 bhp @ 6100 rpm",
    topSpeed: "100 km/h",
    mileage: "35-40 kmpl",
    fuelCapacity: "13 L",
    weight: "185 kg",
    price: "₹1,69,000",
    description: "The latest 2024 Standard 350 with enhanced reliability and modern touches.",
    features: ["Electric Start", "Minimalist Design", "Improved Engine", "Single Channel ABS"],
    colors: ["Jet Black", "Forest Green", "Ash Grey"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2024,
    category: "new",
  },
  {
    id: 8,
    name: "Standard 350 (2023)",
    image: "/royal-enfield-black-side.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "349cc",
    torque: "27 Nm @ 4000 rpm",
    power: "20.2 bhp @ 6100 rpm",
    topSpeed: "100 km/h",
    mileage: "35-40 kmpl",
    fuelCapacity: "13 L",
    weight: "185 kg",
    price: "₹1,64,000",
    description: "The no-nonsense Standard 350 - pure motorcycling essence without frills.",
    features: ["Kick Start", "Minimalist Design", "Authentic Royal Enfield Experience"],
    colors: ["Jet Black", "Forest Green"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2023,
    category: "new",
  },
  {
    id: 9,
    name: "Standard 350 (2022)",
    image: "/royal-enfield-green-classic.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "349cc",
    torque: "27 Nm @ 4000 rpm",
    power: "20.2 bhp @ 6100 rpm",
    topSpeed: "100 km/h",
    mileage: "35-40 kmpl",
    fuelCapacity: "13 L",
    weight: "185 kg",
    price: "₹1,59,000",
    description: "The 2022 Standard 350 with refined engineering and classic appeal.",
    features: ["Improved Reliability", "Classic Styling", "Affordable Entry Point"],
    colors: ["Battle Green", "Jet Black"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2022,
    category: "new",
  },
  {
    id: 10,
    name: "Standard 350 (2021)",
    image: "/royal-enfield-standard-350-2021.png",
    engine: "Single Cylinder, 4-Stroke, Air-Oil Cooled",
    displacement: "349cc",
    torque: "27 Nm @ 4000 rpm",
    power: "20.2 bhp @ 6100 rpm",
    topSpeed: "98 km/h",
    mileage: "35-40 kmpl",
    fuelCapacity: "13 L",
    weight: "183 kg",
    price: "₹1,54,000",
    description: "The 2021 Standard 350 - first year of the new generation engine.",
    features: ["New Generation Engine", "Improved Fuel Efficiency", "Classic Design"],
    colors: ["Jet Black", "Battle Green"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2021,
    category: "new",
  },
  {
    id: 11,
    name: "Standard 350 (2020)",
    image: "/royal-enfield-standard-350-2020.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.1 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "187 kg",
    price: "₹1,45,000",
    description: "The 2020 Standard 350 with the classic UCE engine and traditional styling.",
    features: ["UCE Engine", "Kick Start", "Traditional Royal Enfield Feel"],
    colors: ["Jet Black", "Regal Red"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2020,
    category: "new",
  },
  {
    id: 12,
    name: "Standard 350 (2019)",
    image: "/royal-enfield-standard-350-2019.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.1 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "187 kg",
    price: "₹1,39,000",
    description: "The 2019 Standard 350 maintaining the authentic Bullet character.",
    features: ["Classic UCE Engine", "Simple Design", "Reliable Performance"],
    colors: ["Jet Black", "Forest Green"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2019,
    category: "new",
  },
  {
    id: 13,
    name: "Standard 350 (2018)",
    image: "/royal-enfield-standard-350-2018.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.1 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "187 kg",
    price: "₹1,34,000",
    description: "The 2018 Standard 350 with improved build quality and reliability.",
    features: ["Enhanced Build Quality", "Classic Styling", "Proven UCE Engine"],
    colors: ["Jet Black", "Bullet Silver"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2018,
    category: "new",
  },
  {
    id: 14,
    name: "Standard 350 (2017)",
    image: "/royal-enfield-standard-350-2017.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.1 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "187 kg",
    price: "₹1,29,000",
    description: "The 2017 Standard 350 continuing the legacy of simple, honest motorcycling.",
    features: ["Time-tested UCE Engine", "Minimalist Approach", "Affordable Classic"],
    colors: ["Jet Black", "Forest Green"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2017,
    category: "new",
  },
  {
    id: 15,
    name: "Standard 350 (2016)",
    image: "/royal-enfield-standard-350-2016.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.1 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "187 kg",
    price: "₹1,24,000",
    description: "The 2016 Standard 350 with refined UCE engine and classic appeal.",
    features: ["Refined UCE Engine", "Classic Chrome", "Traditional Design"],
    colors: ["Jet Black", "Maroon"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2016,
    category: "new",
  },
  {
    id: 16,
    name: "Electra 350",
    image: "/royal-enfield-electra-350.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "28 Nm @ 4000 rpm",
    power: "19.8 bhp @ 5250 rpm",
    topSpeed: "95 km/h",
    mileage: "37-42 kmpl",
    fuelCapacity: "13.5 L",
    weight: "193 kg",
    price: "Heritage Model",
    description: "The Electra 350 - combining classic Bullet DNA with electric start convenience.",
    features: ["Electric Start", "Classic Chrome", "Heritage Styling"],
    colors: ["Royal Blue", "Maroon", "Black"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 2010,
    category: "new",
  },
  {
    id: 17,
    name: "Bullet 350 (1970)",
    image: "/royal-enfield-vintage-bullet-1970.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "25 Nm @ 3500 rpm",
    power: "18 bhp @ 5000 rpm",
    topSpeed: "85 km/h",
    mileage: "30-35 kmpl",
    fuelCapacity: "12 L",
    weight: "180 kg",
    price: "Classic Heritage",
    description: "The legendary 1970 Bullet - pure vintage motorcycling with authentic character.",
    features: ["Kick Start Only", "Cast Iron Engine", "Classic Chrome Finish"],
    colors: ["Black", "Maroon"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1970,
    category: "vintage",
  },
  {
    id: 18,
    name: "Bullet 350 (1980)",
    image: "/royal-enfield-vintage-bullet-1980.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "26 Nm @ 3800 rpm",
    power: "18.5 bhp @ 5100 rpm",
    topSpeed: "90 km/h",
    mileage: "32-37 kmpl",
    fuelCapacity: "12.5 L",
    weight: "185 kg",
    price: "Vintage Collection",
    description: "The 1980s Bullet with improved reliability while maintaining classic appeal.",
    features: ["Improved Carburetor", "Better Electrics", "Traditional Styling"],
    colors: ["Black", "Blue", "Maroon"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1980,
    category: "vintage",
  },
  {
    id: 19,
    name: "Bullet Diesel Taurus (1990)",
    image: "/royal-enfield-diesel-bullet-1990.png",
    engine: "Single Cylinder, 4-Stroke, Diesel",
    displacement: "325cc",
    torque: "15 Nm @ 2500 rpm",
    power: "6.5 bhp @ 3600 rpm",
    topSpeed: "65 km/h",
    mileage: "72-85 kmpl",
    fuelCapacity: "11 L",
    weight: "175 kg",
    price: "Rare Heritage",
    description: "The unique diesel Bullet Taurus - an engineering marvel with incredible fuel efficiency.",
    features: ["Diesel Engine", "Exceptional Mileage", "Unique Sound Character"],
    colors: ["Black", "Green"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1990,
    category: "vintage",
  },
  {
    id: 20,
    name: "Bullet 350 (1955)",
    image: "/royal-enfield-bullet-1955.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "346cc",
    torque: "22 Nm @ 3200 rpm",
    power: "16 bhp @ 4800 rpm",
    topSpeed: "75 km/h",
    mileage: "28-32 kmpl",
    fuelCapacity: "11 L",
    weight: "170 kg",
    price: "Heritage Classic",
    description: "The original 1955 Bullet - where the legend began with authentic British engineering.",
    features: ["Cast Iron Engine", "Kick Start Only", "Original British Design"],
    colors: ["Black", "Maroon"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1955,
    category: "vintage",
  },
  {
    id: 21,
    name: "Bullet 500 (1960)",
    image: "/royal-enfield-bullet-500-1960.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "499cc",
    torque: "35 Nm @ 3000 rpm",
    power: "22 bhp @ 4500 rpm",
    topSpeed: "95 km/h",
    mileage: "25-30 kmpl",
    fuelCapacity: "12 L",
    weight: "185 kg",
    price: "Vintage Legend",
    description: "The powerful 1960 Bullet 500 - more displacement, more character.",
    features: ["Larger Engine", "Chrome Tank", "Classic British Styling"],
    colors: ["Black", "Blue", "Green"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1960,
    category: "vintage",
  },
  {
    id: 22,
    name: "Crusader 250 (1965)",
    image: "/royal-enfield-crusader-250-1965.png",
    engine: "Single Cylinder, 2-Stroke",
    displacement: "248cc",
    torque: "18 Nm @ 4000 rpm",
    power: "15 bhp @ 5500 rpm",
    topSpeed: "85 km/h",
    mileage: "35-40 kmpl",
    fuelCapacity: "10 L",
    weight: "140 kg",
    price: "Rare Classic",
    description: "The sporty 1965 Crusader 250 - Royal Enfield's venture into 2-stroke performance.",
    features: ["2-Stroke Engine", "Lightweight", "Sport Styling"],
    colors: ["Red", "Black", "Silver"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1965,
    category: "vintage",
  },
  {
    id: 23,
    name: "Continental GT (1965)",
    image: "/royal-enfield-continental-gt-1965.png",
    engine: "Single Cylinder, 4-Stroke, Air Cooled",
    displacement: "248cc",
    torque: "20 Nm @ 4500 rpm",
    power: "21 bhp @ 7000 rpm",
    topSpeed: "105 km/h",
    mileage: "30-35 kmpl",
    fuelCapacity: "11 L",
    weight: "155 kg",
    price: "Cafe Racer Legend",
    description: "The original 1965 Continental GT - the first cafe racer from Royal Enfield.",
    features: ["Clip-on Handlebars", "Racing Position", "High Performance"],
    colors: ["Racing Green", "Black", "Silver"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1965,
    category: "vintage",
  },
  {
    id: 24,
    name: "Interceptor 750 (1969)",
    image: "/royal-enfield-interceptor-750-1969.png",
    engine: "Parallel Twin, 4-Stroke, Air Cooled",
    displacement: "736cc",
    torque: "55 Nm @ 4000 rpm",
    power: "58 bhp @ 6500 rpm",
    topSpeed: "185 km/h",
    mileage: "20-25 kmpl",
    fuelCapacity: "15 L",
    weight: "210 kg",
    price: "Ultimate Classic",
    description: "The legendary 1969 Interceptor 750 - Royal Enfield's most powerful vintage twin.",
    features: ["Twin Cylinder", "High Performance", "Racing Heritage"],
    colors: ["Blue", "Black", "Red"],
    originalSiteUrl: "https://www.royalenfield.com/in/en/motorcycles/",
    year: 1969,
    category: "vintage",
  },
]

export default function Home() {
  const [filter, setFilter] = useState<"all" | "new" | "vintage">("all")

  const filteredBikes = useMemo(() => {
    if (filter === "all") return royalEnfieldBikes
    return royalEnfieldBikes.filter((bike) => bike.category === filter)
  }, [filter])

  return (
    <main className="min-h-screen bg-background">
      <Header onFilterChange={setFilter} currentFilter={filter} />

      <div className="pt-20">
        <HeroSection />

        <section id="models-section" className="py-16 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-4xl font-bold text-foreground mb-4">Our Motorcycle Collection</h2>
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                Discover the complete range of Royal Enfield motorcycles, from vintage classics to modern marvels, each
                crafted with precision and built for the pure motorcycling experience.
              </p>
              <div className="mt-4">
                <span className="text-sm text-accent">
                  Showing {filteredBikes.length} {filter === "all" ? "models" : `${filter} models`}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-6 lg:gap-8">
              {filteredBikes.map((bike) => (
                <BikeCard key={bike.id} bike={bike} />
              ))}
            </div>
          </div>
        </section>

        <SpecsSection />

        <section className="py-16 px-4 bg-muted/30">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl font-bold text-foreground mb-8">Made By</h2>
            <div className="flex flex-wrap justify-center gap-8 text-lg">
              <div className="glass p-6 rounded-lg">
                <h3 className="font-bold text-accent text-xl mb-2">Athar Khan</h3>
                <p className="text-muted-foreground">Lead Developer</p>
              </div>
              <div className="glass p-6 rounded-lg">
                <h3 className="font-bold text-accent text-xl mb-2">Pranav Bhave</h3>
                <p className="text-muted-foreground">Frontend Specialist</p>
              </div>
              <div className="glass p-6 rounded-lg">
                <h3 className="font-bold text-accent text-xl mb-2">Anmay Koli</h3>
                <p className="text-muted-foreground">Design Engineer</p>
              </div>
            </div>
            <p className="text-muted-foreground mt-8 text-sm">
              Crafted with passion for Royal Enfield enthusiasts worldwide
            </p>
          </div>
        </section>
      </div>
    </main>
  )
}
